### ISSUE TITLE
rapid branch does not respect multiple indexes

### ISSUE THREAD

**Issue by GregOnNet** [philiptober/rapid-git#11]
When I want to rapidly clean local branches `rapid branch` only deletes the first index.
`rapid branch` should behave like `rapid track` and `rapid stage`.

![2016-03-29 10_46_36-_workbench_projects_co-it_homepage](https://cloud.githubusercontent.com/assets/444278/14102592/d372fd5c-f59b-11e5-9dfc-99d8ce78fe5c.png)

**Comment by philiptober** [comment]
You can test an implementation for it with the branch **enhancement/issue-#11**
On this branch, multiple indexes and ranges work for:
- `rapid branch -d <indexes and ranges>`
- `rapid branch -D <indexes and ranges>`

The generated output is the default output of `git branch [-d | -D]`. Please tell me, if you want a restyled one or additional information or anything like that.

Tested on Mac with:
- ZSH 5.0.8
- BASH 4.3.39

**Comment by philiptober** [comment]
merged into master
