### ISSUE TITLE
Provide rapid push 

### ISSUE THREAD

**Issue by GregOnNet** [philiptober/rapid-git#12]
In the last few days I started to push my feature-branches more often.

**Why?**
- Saving my changes on the server
- Enabling colleagues to work on issues when I am ill or something like that

I think it would be valuable to provide the command `rapid push <index>` pushing a branch by it's index.
To keep things a bit simple `origin` should be the default target to push any changes.
Furthermore it should be possible to delete the remote-branch via `rapid push <index> --delete`.

What do you think about this idea?

Kinds
Gregor

**Comment by philiptober** [comment]
Well, I often have to push different branches too. So I like the idea. Maybe Alexander has some valuable pros or cons to contribute?

**Comment by philiptober** [comment]
You can test an implementation for it with the branch **enhancement/issue-#12**
On this branch, multiple indexes and ranges work for:
- `rapid push [ --delete ] <indexes and ranges>`

Currently there is no way to change the remote. It is always origin. Also, there are no safety measures put in place. So it is quite easy to delete many remote branches in one go.

**enhancement/issue-#12** is branched off **enhancement/issue-#11**. So you can also use the experimental:
- `rapid branch [ -d | -D ] <indexes and ranges>``

Tested on Mac with:
-ZSH 5.0.8

**Comment by GregOnNet** [comment]
Sounds good.
I will going to check this tomorrow when I sit in the train back to Leipzig.

In my opinion we shall not allow to push ranges.
My use case is just about pushing and deleting one single branch.

I have no use case in mind where I have to push multiple branches.

To avoid unintentionally pushes of branches I vote to remove the possibility to push a range of branches.

**Comment by philiptober** [comment]
I do not mind changing it back to one branch per push. We most likely only seldom encounter use cases, where we want to push multiple branches. Although maybe Alex have had different experiences?

**Comment by philiptober** [comment]
Updated rapid push:
`rapid push [ git args... ] <index>`

`[ git args... ]` includes `--delete` as well as `[ <refspec>... ]` Well basically any arg but `<repository>` of `git push`

**Comment by philiptober** [comment]
merged into master
