### ISSUE TITLE
Switching to rust?

### ISSUE THREAD

**Issue by GregOnNet** [philiptober/rapid-git#19]
The issues #15 and #16 mean an increasing complexety to our shell-script.
I see problems maintaining this project in the future if we stick to this kind of scripting.

My idea is to switch to another platform providing a way to modularize rapid-git and to improve performance.

I heard of [Rust](https://www.rust-lang.org/) providing effective C-Bindings and type inference.
I suggest a kind of coding dojo, taking about 2-4 hours time to evaluate Rust.
After that we may decide if a switch makes sense or not.

What do you think @philiptober, @agross?

**Comment by GregOnNet** [comment]
There are bindings for Rust using libgit2. Maybe we can improve performance using this library instead of calling git cli: http://alexcrichton.com/git2-rs/git2 ([Repo](https://github.com/alexcrichton/git2-rs))

**Comment by agross** [comment]
Will Rust compile down to native binaries or will our users have to install a runtime?

**Comment by GregOnNet** [comment]
As far as i know it compiles to a native binary. I just started to play
with rust on Windows.
Running `rustc` creates an executable.

Alexander Groß notifications@github.com schrieb am Di., 18. Okt. 2016
00:18:

**Comment by GregOnNet** [comment]
We do not plan to rewrite rapid-git yet.
It does its job.
